package com.ysoft.dctrl.slicer.param;

/**
 * Created by kuhn on 4/4/2017.
 */

/**
 * Slicer independent parameters.
 */
public enum SlicerParamType {
    //machine
    MACHINE_WIDTH, MACHINE_HEIGHT, MACHINE_DEPTH,

    //speed
    SPEED_PRINT,SPEED_OUTER_WALL,SPEED_INNER_WALL,SPEED_SOLID_LAYERS,SPEED_WALL,

    //resolution
    LAYER_HEIGHT, LAYER_HEIGHT_0,

    //shell
    SHELL_THICKNESS,SHELL_TOP_BOTTOM_THICKNESS,SHELL_TOP_LAYERS, SHELL_BOTTOM_LAYERS,
    SHELL_TOP_THICKNESS,

    //infill
    INFILL_OVERLAP_PERCENTAGE, INFILL_LAYER_THICKNESS, INFILL_PATTERN, INFILL_DENSITY,

    //material
    MATERIAL_PRINT_TEMPERATURE_DEFAULT, MATERIAL_PRINT_TEMPERATURE, MATERIAL_PRINT_TEMPERATURE_0,
    MATERIAL_DIAMETER, MATERIAL_RETRACT_AT_LAYER_CHANGE, MATERIAL_FLOW, MATERIAL_RETRACTION_DISTANCE,
    MATERIAL_RETRACTION_SPEED, MATERIAL_RETRACTION_PRIME_SPEED, MATERIAL_RETRACTION_MINIMUM_TRAVEL,


    //cooling
    COOL_FAN_REGMAX_SPEED_THRESHOLD, COOL_FAN_SPEED_REG_LAYER,

    //support
    SUPPORT_ENABLED, SUPPORT_BUILDPLATE_TYPE, SUPPORT_DENSITY, SUPPORT_PATTERN, SUPPORT_ANGLE,

    //
    START_GCODE, END_GCODE
}
