package com.ysoft.dctrl.event;

/**
 * Created by pilar on 30.3.2017.
 */
public enum EventType {
    OPEN_MODEL,
    CHANGE_LANGUAGE,
    ADD_MODEL,
    PRINTER_CHANGED,
    SLICER_PARAM_CHANGED,
    SLICER_SCENE_EXPORT,
    SLICER_SCENE_EXPORTED,
    SLICER_START,
    SLICER_STOP,
    SLICER_FINISHED,
    SLICER_PROGRESS,
    SLICER_BACK_TO_EDIT,
    CONTROL_MOVE_MODEL_CLICK,
    CONTROL_SCALE_MODEL_CLICK,
    CONTROL_ROTATE_MODEL_CLICK,
    MODEL_SELECTED,
    MODEL_LOAD_PROGRESS,
    MODEL_LOADED, RESET_VIEW,
    CENTER_SELECTED_MODEL
}
