package com.ysoft.dctrl.event;

/**
 * Created by pilar on 30.3.2017.
 */
public enum EventType {
    OPEN_MODEL,
    CHANGE_LANGUAGE,
    ADD_MODEL,
    PRINTER_CHANGED,
    EXPORT_SCENE,
    SCENE_EXPORTED,
    SLICER_PARAM_CHANGED,
    SLICER_PARAM_CHANGE,
    SLICE_STARTED,
    SLICE_DONE,
    CONTROL_MOVE_MODEL_CLICK,
    CONTROL_SCALE_MODEL_CLICK,
    CONTROL_ROTATE_MODEL_CLICK,
    MODEL_SELECTED,
    MODEL_LOAD_PROGRESS,
    MODEL_LOADED, RESET_VIEW,
    CENTER_SELECTED_MODEL,
    ALIGN_LEFT_SELECTED_MODEL,
    ALIGN_RIGHT_SELECTED_MODEL,
    ALIGN_FRONT_SELECTED_MODEL,
    ALIGN_BACK_SELECTED_MODEL,
    SHOW_DIALOG,
    TAKE_SCENE_SNAPSHOT,
    JOB_FILE_PROGRESS,
    JOB_FILE_DONE,
    JOB_SEND_DONE,
    SHOW_NOTIFICATION
}
